if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('$HOME/.vim-plugged')
Plug 'tpope/vim-surround'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-unimpaired'
Plug 'noahfrederick/vim-hemisu'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'raimondi/delimitmate'
Plug 'mhinz/vim-startify'
Plug 'mhinz/vim-signify'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ntpeters/vim-better-whitespace'
Plug 'sheerun/vim-polyglot'
Plug 'itchyny/lightline.vim'
Plug 'Chiel92/vim-autoformat'

" Load the local config. Put it here so that we can use other plugins as well.
if !empty(glob("~/.vimrc.local"))
  source ~/.vimrc_local
endif

call plug#end()

set nu cursorline
inoremap jk <ESC>
xnoremap jk <ESC>
vnoremap jk <ESC>
nnoremap gQ gqap

" Center the cursor on the screen after a search
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
set lazyredraw
set nofoldenable
set tabstop=2 softtabstop=2 shiftwidth=2
set ignorecase smartcase incsearch hls
set encoding=utf8
set bg=dark

" disable auto insert comment prefix
set formatoptions-=cro

" set python3 host
let g:python3_host_prog='/usr/bin/python3'

" make the backgrond color work with tmux over ssh
" https://superuser.com/a/562423
set t_ut=

" Plugin mappings
nmap <c-p> :Files<CR>
nnoremap <C-\> :NERDTreeToggle<CR>
nnoremap <A-\> :NERDTreeFind<CR>

try
    colorscheme hemisu
catch /^Vim\%((\a\+)\)\=:E185/
  " ignore it, the theme might not be installed yet
endtry
